### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by superkido511** [floriankagerer/bed-bpp-env#3]
Thanks for your great work !
Could you add a license file? I want to use the code in my experiments

**Comment by floriankagerer** [comment]
Hi superkido511, 
thank you for your kind words, I really appreciate it.

I added the MIT license to this repository.

If you plan to publish a paper, I would be happy if you cite the paper https://journals.sagepub.com/doi/10.1177/02783649231193048

Greetings from Austria,
Florian
