### ISSUE TITLE
Training configs for Online-3D-BPP-PCT models

### ISSUE THREAD

**Issue by superkido511** [floriankagerer/bed-bpp-env#5]
Hello, could you provide more details about which box generator did you use to train the models in alexfrom0815_O3D-BPP-PCT/Online-3D-BPP-PCT-main/pt_models ?

From the archived source code, it seems to be the random box generator at 
https://github.com/floriankagerer/bed-bpp-env/blob/5af526ae4d25844b656635b77e56c4429f0ad600/alexfrom0815_O3D-BPP-PCT/Online-3D-BPP-PCT-main/pct_envs/PctDiscrete0/binCreator.py#L24

However, I don't see any logics to ensure that the random sampled boxes will fit the container, which might result in impossible orders during training.

**Comment by floriankagerer** [comment]
Hello superkido511,
I hope to correctly understand your question: you want to make sure that if you train a model, the box sizes that are randomly sampled all fit int the container, right?

To train the models, I used the default settings. Thus, you are right that the `RandomBoxCreator` was used to sample the boxes (cf. [PctDiscrete0/bin3D.py#L33](https://github.com/floriankagerer/bed-bpp-env/blob/5af526ae4d25844b656635b77e56c4429f0ad600/alexfrom0815_O3D-BPP-PCT/Online-3D-BPP-PCT-main/pct_envs/PctDiscrete0/bin3D.py#L33))

When creating the environment, we provide the `item_size_set` that is specified in the [arguments](https://github.com/floriankagerer/bed-bpp-env/blob/5af526ae4d25844b656635b77e56c4429f0ad600/alexfrom0815_O3D-BPP-PCT/Online-3D-BPP-PCT-main/tools.py#L186). Similarly for the `container_size`.

For this reason, I modified the variables `container_size` and `item_size_set` in [givenData.py](https://github.com/floriankagerer/bed-bpp-env/blob/main/alexfrom0815_O3D-BPP-PCT/Online-3D-BPP-PCT-main/givenData.py)

With these changes it should be possible that every box fits inside the container.

Let me know if this answer helps you.

Best regards,
Florian

**Comment by superkido511** [comment]
Thanks for your quick response!
If I understand correctly, the RandomBoxCreator give the agent a random box from item_size_set, then the agent need to learn how to place the box into the container in the most optimal way. If that's the case, what if large boxes are chosen consecutively and there is no way to fit them all in the container? For example, the container size is [10, 10, 10] but 9 x [5, 5, 5] box are chosen? In this case, there are no solution.
In some other box generator like CUT-1 or CUT-2, they cut boxes in the container to smaller boxes, sort, then give each box to the agent, so there are at least 1 solution to place all the boxes into the container.
Sorry If my understanding is incorrect.

**Comment by superkido511** [comment]
Anyways, I think it doesn't really matter if the next generated box can't be placed in the container. Really appreciate for your help. I will continue to consult the original author about this.
